name: My First Github Action
on: [push]
jobs:
 build-app:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: 16
     - name: Install node_modules
       run: yarn
     - name: Build the project
       run: yarn build
     - name: Deploying the project
       env: 
        VERCEL_ORG_ID: JVamji7Q30Qms1qG6hNA5BFA
        VERCEL_PROD_ID: prj_n7il0Q4JlhkPbNERy3WBLuIsRvWP
       run: yarn deploy
     - name: Setup finish
       run: echo "Hurray!" 
    
    